use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};
use termy_command_core::{CommandId, KeybindPlatform, default_keybinds_for_platform};

fn main() {
    if let Err(error) = run() {
        eprintln!("{}", error);
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let mut args = std::env::args().skip(1);
    let Some(command) = args.next() else {
        bail!("usage: cargo run -p xtask -- generate-keybindings-doc [--check]");
    };

    if command != "generate-keybindings-doc" {
        bail!(
            "unknown xtask command `{}`; expected `generate-keybindings-doc`",
            command
        );
    }

    let mut check_only = false;
    for arg in args {
        match arg.as_str() {
            "--check" => check_only = true,
            other => bail!("unknown argument `{}`", other),
        }
    }

    let contents = render_keybindings_doc();
    let doc_path = docs_keybindings_path()?;

    if check_only {
        let existing = std::fs::read_to_string(&doc_path)
            .with_context(|| format!("failed to read {}", doc_path.display()))?;
        if existing == contents {
            println!("keybindings docs are up to date");
            return Ok(());
        }
        bail!(
            "keybindings docs are out of date; run `cargo run -p xtask -- generate-keybindings-doc`"
        );
    }

    std::fs::write(&doc_path, contents)
        .with_context(|| format!("failed to write {}", doc_path.display()))?;
    println!("updated {}", doc_path.display());
    Ok(())
}

fn docs_keybindings_path() -> Result<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .context("failed to compute workspace root")?;
    Ok(workspace_root.join("docs/keybindings.md"))
}

fn render_keybindings_doc() -> String {
    let mut output = String::new();

    output.push_str("# Keybindings\n\n");
    output.push_str("_This file is generated by `cargo run -p xtask -- generate-keybindings-doc`. Do not edit manually._\n\n");
    output.push_str("Termy keybindings use Ghostty-style trigger overrides via repeated `keybind` lines in `~/.config/termy/config.txt`.\n\n");

    output.push_str("## Default Keybinds\n\n");
    for platform in KeybindPlatform::ALL {
        output.push_str(&format!("### {}\n\n", platform_title(platform)));
        for binding in default_keybinds_for_platform(platform) {
            output.push_str(&format!(
                "- `{}` -> `{}`\n",
                binding.trigger,
                binding.action.config_name()
            ));
        }
        output.push('\n');
    }

    output.push_str("`secondary` maps to `cmd` on macOS and `ctrl` on non-macOS platforms.\n\n");

    output.push_str("## Config Syntax\n\n");
    output.push_str("Supported forms:\n\n");
    output.push_str("- `keybind = clear`\n");
    output.push_str("- `keybind = <trigger>=<action>`\n");
    output.push_str("- `keybind = <trigger>=unbind`\n\n");
    output.push_str("Behavior:\n\n");
    output.push_str("- Directives are applied in file order.\n");
    output.push_str("- Later lines win for the same trigger.\n");
    output.push_str("- `clear` removes all defaults before later lines are applied.\n");
    output.push_str("- `unbind` removes the current mapping for a trigger.\n");
    output.push_str("- Invalid lines are ignored (with warnings).\n\n");

    output.push_str("Related UI option:\n\n");
    output.push_str("- `command_palette_show_keybinds = true|false` controls whether command palette rows show shortcut badges.\n\n");

    output.push_str("## Configurable Actions\n\n");
    for action in CommandId::all_config_names() {
        output.push_str(&format!("- `{}`\n", action));
    }

    output.push_str("\n## Customization Examples\n\n");
    output.push_str("### 1) Override one default\n\n");
    output.push_str("```txt\nkeybind = cmd-p=toggle_command_palette\n```\n\n");
    output.push_str("### 2) Remove one default\n\n");
    output.push_str("```txt\nkeybind = cmd-w=unbind\n```\n\n");
    output.push_str("### 3) Start from scratch\n\n");
    output.push_str("```txt\nkeybind = clear\nkeybind = cmd-p=toggle_command_palette\nkeybind = cmd-t=new_tab\nkeybind = cmd-w=close_tab\nkeybind = cmd-c=copy\nkeybind = cmd-v=paste\n```\n\n");
    output.push_str("### 4) Use `secondary` for cross-platform configs\n\n");
    output.push_str("```txt\nkeybind = secondary-p=toggle_command_palette\nkeybind = secondary-t=new_tab\n```\n");

    output
}

fn platform_title(platform: KeybindPlatform) -> &'static str {
    match platform {
        KeybindPlatform::MacOs => "macOS Defaults",
        KeybindPlatform::Windows => "Windows Defaults",
        KeybindPlatform::Linux => "Linux Defaults",
        KeybindPlatform::Other => "Other Platform Defaults",
    }
}
