/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ThemesRouteImport } from "./routes/themes"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ReleasesIndexRouteImport } from "./routes/releases/index"
import { Route as DocsIndexRouteImport } from "./routes/docs/index"
import { Route as ReleasesTagRouteImport } from "./routes/releases/$tag"
import { Route as DocsSplatRouteImport } from "./routes/docs/$"

const ThemesRoute = ThemesRouteImport.update({
  id: "/themes",
  path: "/themes",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: "/releases/",
  path: "/releases/",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesTagRoute = ReleasesTagRouteImport.update({
  id: "/releases/$tag",
  path: "/releases/$tag",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/themes": typeof ThemesRoute
  "/docs/$": typeof DocsSplatRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/docs/": typeof DocsIndexRoute
  "/releases/": typeof ReleasesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/themes": typeof ThemesRoute
  "/docs/$": typeof DocsSplatRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/docs": typeof DocsIndexRoute
  "/releases": typeof ReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/themes": typeof ThemesRoute
  "/docs/$": typeof DocsSplatRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/docs/": typeof DocsIndexRoute
  "/releases/": typeof ReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/themes"
    | "/docs/$"
    | "/releases/$tag"
    | "/docs/"
    | "/releases/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/themes" | "/docs/$" | "/releases/$tag" | "/docs" | "/releases"
  id:
    | "__root__"
    | "/"
    | "/themes"
    | "/docs/$"
    | "/releases/$tag"
    | "/docs/"
    | "/releases/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemesRoute: typeof ThemesRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ReleasesTagRoute: typeof ReleasesTagRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/themes": {
      id: "/themes"
      path: "/themes"
      fullPath: "/themes"
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/releases/": {
      id: "/releases/"
      path: "/releases"
      fullPath: "/releases/"
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/": {
      id: "/docs/"
      path: "/docs"
      fullPath: "/docs/"
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/releases/$tag": {
      id: "/releases/$tag"
      path: "/releases/$tag"
      fullPath: "/releases/$tag"
      preLoaderRoute: typeof ReleasesTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/$": {
      id: "/docs/$"
      path: "/docs/$"
      fullPath: "/docs/$"
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemesRoute: ThemesRoute,
  DocsSplatRoute: DocsSplatRoute,
  ReleasesTagRoute: ReleasesTagRoute,
  DocsIndexRoute: DocsIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
